In [1]:
import numpy as np

In [2]:
a = np.genfromtxt('data25.csv', skip_header=1, delimiter=",")
a

array([ 1.,  2.,  3.,  4.,  5.,  0.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,
        3.,  4.,  5.,  0.,  1.,  2.,  3.,  6.,  7.,  8.,  9., -1.])

In [4]:
len(a), a.size, a.shape, a.ndim

(25, 25, (25,), 1)

In [6]:
b = a.reshape((5,5))
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  1.,  2.,  3.,  4.],
       [ 5.,  0.,  1.,  2.,  3.],
       [ 6.,  7.,  8.,  9., -1.]])

In [8]:
len(b), b.size, b.shape, b.ndim

(5, 25, (5, 5), 2)

In [9]:
np.sum(b,axis=1)

array([15., 10., 15., 11., 29.])

In [11]:
np.sum(b,axis=0)

array([17., 11., 16., 21., 15.])

In [12]:
np.mean(b,axis=1)

array([3. , 2. , 3. , 2.2, 5.8])

In [13]:
np.min(b,axis=1)

array([ 1.,  0.,  1.,  0., -1.])

In [14]:
np.max(b,axis=1)

array([5., 4., 5., 5., 9.])

In [15]:
np.median(b,axis=1)

array([3., 2., 3., 2., 7.])

In [16]:
np.savetxt('array_b.txt', b, delimiter =',')

In [17]:
b2 = np.genfromtxt('array_b.txt', delimiter=",")
b2

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  1.,  2.,  3.,  4.],
       [ 5.,  0.,  1.,  2.,  3.],
       [ 6.,  7.,  8.,  9., -1.]])

**Масъала.** Массиви 3-ченака ба файл сабт карда шавад.

In [18]:
c = a[:6]
c

array([1., 2., 3., 4., 5., 0.])

In [19]:
np.median(c)

np.float64(2.5)

In [21]:
c.sort()
c

array([0., 1., 2., 3., 4., 5.])

In [22]:
c = a[:7]
print(np.median(c))
print(c)
c.sort()
print(c)

2.0
[0. 1. 2. 3. 4. 5. 1.]
[0. 1. 1. 2. 3. 4. 5.]


In [25]:
print(np.unique(a))
print(a)

[-1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[ 0.  1.  1.  2.  3.  4.  5.  2.  3.  4.  5.  1.  2.  3.  4.  5.  0.  1.
  2.  3.  6.  7.  8.  9. -1.]


In [26]:
print(np.unique(b))
print(b)

[-1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[ 0.  1.  1.  2.  3.]
 [ 4.  5.  2.  3.  4.]
 [ 5.  1.  2.  3.  4.]
 [ 5.  0.  1.  2.  3.]
 [ 6.  7.  8.  9. -1.]]


In [27]:
print(c)
print(np.unique(c))

[0. 1. 1. 2. 3. 4. 5.]
[0. 1. 2. 3. 4. 5.]
